### ISSUE TITLE
Deprecate datablocks

### ISSUE THREAD

**Issue by phyy-nx** [mewall/lunus#10]
Datablocks are a dials construct that are due to be deprecated in favor of ExperimentLists, and indeed cctbx/dxtbx#504 is a PR where they are finally removed.  The following files in lunus use datablocks and need to be updated to use ExperimentLists instead:

These scripts are unused and can be removed:
- [ ] ./scripts/index_cctbx.py
- [ ] ./scripts/index_cctbx_old.py
- [ ] ./scripts/integrate_diffuse_dials.py
- [ ] ./scripts/integrate_diffuse_dials_cypa.py
- [ ] ./scripts/integrate_diffuse_dials_trypsin.py
- [ ] ./scripts/lightweight_index.py

This script is likely unused, @mewall will verify
- [ ] ./lunus/command_line/stills_process.py

The currently active script is ./lunus/command_line/lunus_stills_process.py, which does not use datablocks.

**Comment by phyy-nx** [comment]
Received feedback from @mewall.  Original post edited with new tasks.

**Comment by mewall** [comment]
> Received feedback from @mewall. Original post edited with new tasks.

Removed all of the named scripts @phyy-nx

**Comment by phyy-nx** [comment]
Looks great!  Thanks!
